---

- name: Include variables specific for the OS family
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- include_tasks: install.yml
- include_tasks: configure.yml
